spring.datasource.url=jdbc:postgresql://localhost:5433/zaderzhania
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.thymeleaf.cache=false

spring.mvc.hiddenmethod.filter.enabled=true

server.port=8080

spring.application.name=zaderhania-web